places = [
    {"espanol": "AFGHANISTAN", "ingles": "AFGANISTÁN"},
    {"espanol": "ALBANIA", "ingles": "ALBANIA"},
    {"espanol": "ALGERIA", "ingles": "ARGELIA"},
    {"espanol": "ANDORRA", "ingles": "ANDORRA"},
    {"espanol": "ANGOLA", "ingles": "ANGOLA"},
    {"espanol": "ANGUILLA", "ingles": "ANGUILLA (RU)"},
    {"espanol": "ANTIGUA AND BARBUDA", "ingles": "ANTIGUA Y BARBUDA"},
    {"espanol": "ARGENTINA", "ingles": "ARGENTINA"},
    {"espanol": "ARMENIA", "ingles": "ARMENIA"},
    {"espanol": "ARUBA", "ingles": "ARUBA (PAISES BAJOS)"},
    {"espanol": "AUSTRALIA", "ingles": "AUSTRALIA"},
    {"espanol": "AUSTRIA", "ingles": "AUSTRIA"},
    {"espanol": "AZERBAIJAN", "ingles": "AZERBAIYÁN"},
    {"espanol": "BAHAMAS", "ingles": "BAHAMAS"},
    {"espanol": "BAHRAIN", "ingles": "BAHREIN"},
    {"espanol": "BANGLADESH", "ingles": "BANGLADESH"},
    {"espanol": "BARBADOS", "ingles": "BARBADOS"},
    {"espanol": "BELARUS", "ingles": "BELARÚS"},
    {"espanol": "BELGIUM", "ingles": "BÉLGICA"},
    {"espanol": "BELIZE", "ingles": "BELICE"},
    {"espanol": "BENIN", "ingles": "BENIN"},
    {"espanol": "BERMUDA", "ingles": "BERMUDAS (RU)"},
    {"espanol": "BHUTAN", "ingles": "BUTÁN"},
    {"espanol": "BOLIVIA (PLURINATIONAL STATE OF)", "ingles": "BOLIVIA"},
    {"espanol": "BONAIRE, SINT EUSTATIUS AND SABA", "ingles": "BONAIRE (PAÍSES BAJOS)"},
    {"espanol": "BOSNIA AND HERZEGOVINA", "ingles": "BOSNIA Y HERZEGOVINA"},
    {"espanol": "BOTSWANA", "ingles": "BOTSWANA"},
    {"espanol": "BRAZIL", "ingles": "BRASIL"},
    {"espanol": "BRITISH VIRGIN ISLANDS", "ingles": "ISLAS VÍRGENES BRITÁNICAS"},
    {"espanol": "BRUNEI DARUSSALAM", "ingles": "BRUNEI DARUSSALAM"},
    {"espanol": "BULGARIA", "ingles": "BULGARIA"},
    {"espanol": "BURKINA FASO", "ingles": "BURKINA FASO"},
    {"espanol": "BURUNDI", "ingles": "BURUNDI"},
    {"espanol": "CABO VERDE", "ingles": "CABO VERDE"},
    {"espanol": "CAMBODIA", "ingles": "CAMBOYA"},
    {"espanol": "CAMEROON", "ingles": "CAMERÚN"},
    {"espanol": "CANADA", "ingles": "CANADÁ"},
    {"espanol": "CAYMAN ISLANDS", "ingles": "ISLAS CAIMÁN"},
    {"espanol": "CENTRAL AFRICAN REPUBLIC", "ingles": "REPÚBLICA CENTROAFRICANA"},
    {"espanol": "CHAD", "ingles": "CHAD"},
    {"espanol": "CHILE", "ingles": "CHILE"},
    {"espanol": "CHINA", "ingles": "CHINA"},
    {"espanol": "COLOMBIA", "ingles": "COLOMBIA"},
    {"espanol": "CONGO", "ingles": "CONGO"},
    {"espanol": "COSTA RICA", "ingles": "COSTA RICA"},
    {"espanol": "CÔTE D\'IVOIRE", "ingles": "COSTA DE MARFIL"},
    {"espanol": "CROATIA", "ingles": "CROACIA"},
    {"espanol": "CUBA", "ingles": "CUBA"},
    {"espanol": "CURAÇAO", "ingles": "CURAZAO (PAÍSES BAJOS)"},
    {"espanol": "CYPRUS", "ingles": "CHIPRE"},
    {"espanol": "CZECHIA", "ingles": "REPÚBLICA CHECA"},
    {"espanol": "DEMOCRATIC REPUBLIC OF THE CONGO", "ingles": "REPLUBICA DOMINICANA DEL CONGO"},
    {"espanol": "DENMARK", "ingles": "DINAMARCA"},
    {"espanol": "DJIBOUTI", "ingles": "YIBUTI"},
    {"espanol": "DOMINICA", "ingles": "DOMINICA"},
    {"espanol": "DOMINICAN REPUBLIC", "ingles": "REPÚBLICA DOMINICANA"},
    {"espanol": "ECUADOR", "ingles": "ECUADOR"},
    {"espanol": "EGYPT", "ingles": "EGIPTO"},
    {"espanol": "EL SALVADOR", "ingles": "EL SALVADOR"},
    {"espanol": "ERITREA", "ingles": "ERITREA"},
    {"espanol": "ESTONIA", "ingles": "ESTONIA"},
    {"espanol": "ESWATINI", "ingles": "SUAZILANDIA"},
    {"espanol": "ETHIOPIA", "ingles": "ETIOPÍA"},
    {"espanol": "FALKLAND ISLANDS (MALVINAS)", "ingles": "ISLAS MALVINAS (RU)"},
    {"espanol": "FAROE ISLANDS", "ingles": "ISLAS FAROE (DINAMARCA)"},
    {"espanol": "FIJI", "ingles": "FIJI"},
    {"espanol": "FINLAND", "ingles": "FINLANDIA"},
    {"espanol": "FRANCE", "ingles": "FRANCIA"},
    {"espanol": "FRENCH GUIANA", "ingles": "GUAYANA FRANCESA (FRANCIA)"},
    {"espanol": "FRENCH POLYNESIA", "ingles": "POLINESIA FRANCESA (FRANCIA)"},
    {"espanol": "GABON", "ingles": "GABÓN"},
    {"espanol": "GAMBIA", "ingles": "GAMBIA"},
    {"espanol": "GEORGIA", "ingles": "GEORGIA"},
    {"espanol": "GERMANY", "ingles": "ALEMANIA"},
    {"espanol": "GHANA", "ingles": "GHANA"},
    {"espanol": "GIBRALTAR", "ingles": "GIBRALTAR (RU)"},
    {"espanol": "GREECE", "ingles": "GRECIA"},
    {"espanol": "GREENLAND", "ingles": "GROENLANDIA"},
    {"espanol": "GRENADA", "ingles": "GRANADA"},
    {"espanol": "GUADELOUPE", "ingles": "GUADALUPE (FRANCIA)"},
    {"espanol": "GUAM", "ingles": "GUAM (EEUU)"},
    {"espanol": "GUATEMALA", "ingles": "GUATEMALA"},
    {"espanol": "GUERNSEY", "ingles": "GUERNSEY (RU)"},
    {"espanol": "PAPUA NEW GUINEA", "ingles": "PAPÚA NUEVA GUINEA"},
    {"espanol": "GUINEA", "ingles": "GUINEA"},
    {"espanol": "EQUATORIAL GUINEA", "ingles": "GUINEA ECUATORIAL"},
    {"espanol": "GUINEA-BISSAU", "ingles": "GUINEA-BISSAU"},
    {"espanol": "GUYANA", "ingles": "GUYANA"},
    {"espanol": "HAITI", "ingles": "HAITÍ"},
    {"espanol": "HOLY SEE", "ingles": "HOLY SEE"},
    {"espanol": "HONDURAS", "ingles": "HONDURAS"},
    {"espanol": "HUNGARY", "ingles": "HUNGRÍA"},
    {"espanol": "ICELAND", "ingles": "ISLANDIA"},
    {"espanol": "INDIA", "ingles": "INDIA"},
    {"espanol": "INDONESIA", "ingles": "INDONESIA"},
    {"espanol": "INTERNATIONAL CONVEYANCE (DIAMOND PRINCESS)", "ingles": "INTERNATIONAL CONVEYANCE (DIAMOND PRINCESS)"},
    {"espanol": "IRAN (ISLAMIC REPUBLIC OF)", "ingles": "IRÁN"},
    {"espanol": "IRAQ", "ingles": "IRAQ"},
    {"espanol": "IRELAND", "ingles": "IRLANDA"},
    {"espanol": "ISLE OF MAN", "ingles": "ISLA DE MAN (RU)"},
    {"espanol": "ISRAEL", "ingles": "ISRAEL"},
    {"espanol": "ITALY", "ingles": "ITALIA"},
    {"espanol": "JAMAICA", "ingles": "JAMAICA"},
    {"espanol": "JAPAN", "ingles": "JAPÓN"},
    {"espanol": "JERSEY", "ingles": "JERSEY (RU)"},
    {"espanol": "JORDAN", "ingles": "JORDANIA"},
    {"espanol": "KAZAKHSTAN", "ingles": "KAZAKISTÁN"},
    {"espanol": "KENYA", "ingles": "KENYA"},
    {"espanol": "KOSOVO[1]", "ingles": "KOSOVO"},
    {"espanol": "KUWAIT", "ingles": "KUWAIT"},
    {"espanol": "KYRGYZSTAN", "ingles": "KIRGUISTÁN"},
    {"espanol": "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "ingles": "LAOS"},
    {"espanol": "LATVIA", "ingles": "LETONIA"},
    {"espanol": "LEBANON", "ingles": "LÍBANO"},
    {"espanol": "LIBERIA", "ingles": "LIBERIA"},
    {"espanol": "LIBYA", "ingles": "LIBIA"},
    {"espanol": "LIECHTENSTEIN", "ingles": "LIECHTENSTEIN"},
    {"espanol": "LITHUANIA", "ingles": "LITUANIA"},
    {"espanol": "LUXEMBOURG", "ingles": "LUXEMBURGO"},
    {"espanol": "MADAGASCAR", "ingles": "MADAGASCAR"},
    {"espanol": "MALAWI", "ingles": "MALAWI"},
    {"espanol": "MALAYSIA", "ingles": "MALAYSIA"},
    {"espanol": "MALDIVES", "ingles": "MALDIVES"},
    {"espanol": "MALI", "ingles": "MALI"},
    {"espanol": "MALTA", "ingles": "MALTA"},
    {"espanol": "MARTINIQUE", "ingles": "MARTINICA (FRANCIA)"},
    {"espanol": "MAURITANIA", "ingles": "MAURITANIA"},
    {"espanol": "MAURITIUS", "ingles": "MAURICIO"},
    {"espanol": "MAYOTTE", "ingles": "MAYOTTE (FRANCIA)"},
    {"espanol": "MEXICO", "ingles": "MÉXICO"},
    {"espanol": "MONACO", "ingles": "MÓNACO"},
    {"espanol": "MONGOLIA", "ingles": "MONGOLIA"},
    {"espanol": "MONTENEGRO", "ingles": "MONTENEGRO"},
    {"espanol": "MONTSERRAT", "ingles": "MONTSERRAT (RU)"},
    {"espanol": "MOROCCO", "ingles": "MARRUECOS"},
    {"espanol": "MOZAMBIQUE", "ingles": "MOZAMBIQUE"},
    {"espanol": "MYANMAR", "ingles": "MYANMAR"},
    {"espanol": "NAMIBIA", "ingles": "NAMIBIA"},
    {"espanol": "NEPAL", "ingles": "NEPAL"},
    {"espanol": "NETHERLANDS", "ingles": "PAÍSES BAJOS"},
    {"espanol": "NEW CALEDONIA", "ingles": "NUEVA CALEDONIA (FRANCIA)"},
    {"espanol": "NEW ZEALAND", "ingles": "NUEVA ZELANDA"},
    {"espanol": "NICARAGUA", "ingles": "NICARAGUA"},
    {"espanol": "NIGER", "ingles": "NÍGER"},
    {"espanol": "NIGERIA", "ingles": "NIGERIA"},
    {"espanol": "NORTH MACEDONIA", "ingles": "MACEDONIA"},
    {"espanol": "NORTHERN MARIANA ISLANDS (COMMONWEALTH OF THE)", "ingles": "ISLAS MARIANAS DEL NORTE (EEUU)"},
    {"espanol": "NORWAY", "ingles": "NORUEGA"},
    {"espanol": "OCCUPIED PALESTINIAN TERRITORY", "ingles": "PALESTINA"},
    {"espanol": "OMAN", "ingles": "OMÁN"},
    {"espanol": "PAKISTAN", "ingles": "PAKISTÁN"},
    {"espanol": "PANAMA", "ingles": "PANAMÁ"},
    {"espanol": "PARAGUAY", "ingles": "PARAGUAY"},
    {"espanol": "PERU", "ingles": "PERÚ"},
    {"espanol": "PHILIPPINES", "ingles": "FILIPINAS"},
    {"espanol": "POLAND", "ingles": "POLONIA"},
    {"espanol": "PORTUGAL", "ingles": "PORTUGAL"},
    {"espanol": "PUERTO RICO", "ingles": "PUERTO RICO (EEUU)"},
    {"espanol": "QATAR", "ingles": "CATAR"},
    {"espanol": "REPUBLIC OF KOREA", "ingles": "REPÚBLICA DE COREA"},
    {"espanol": "REPUBLIC OF MOLDOVA", "ingles": "MOLDOVIA"},
    {"espanol": "RÉUNION", "ingles": "REUNIÓN (FRANCIA)"},
    {"espanol": "ROMANIA", "ingles": "RUMANIA"},
    {"espanol": "RUSSIAN FEDERATION", "ingles": "RUSIA"},
    {"espanol": "RWANDA", "ingles": "RUANDA"},
    {"espanol": "SAINT BARTHÉLEMY", "ingles": "SAINT BARTHÉLEMY"},
    {"espanol": "SAINT KITTS AND NEVIS", "ingles": "SAN CRISTÓBAL Y NIEVES"},
    {"espanol": "SAINT LUCIA", "ingles": "SANTA LUCÍA"},
    {"espanol": "SAINT MARTIN", "ingles": "SAINT MARTIN"},
    {"espanol": "SAINT PIERRE AND MIQUELON", "ingles": "SAN PEDRO Y MIQUELÓN (FRANCIA)"},
    {"espanol": "SAINT VINCENT AND THE GRENADINES", "ingles": "SAN VICENTE Y LAS GRANADINAS"},
    {"espanol": "SAN MARINO", "ingles": "SAN MARINO"},
    {"espanol": "SÃO TOMÉ AND PRÍNCIPE", "ingles": "SAO TOME Y PRINCIPE"},
    {"espanol": "SAUDI ARABIA", "ingles": "ARABIA SAUDITA"},
    {"espanol": "SENEGAL", "ingles": "SENEGAL"},
    {"espanol": "SERBIA", "ingles": "SERBIA"},
    {"espanol": "SEYCHELLES", "ingles": "SEYCHELLES"},
    {"espanol": "SIERRA LEONE", "ingles": "SIERRA LEONA"},
    {"espanol": "SINGAPORE", "ingles": "SINGAPUR"},
    {"espanol": "SINT MAARTEN", "ingles": "SINT MAARTEN"},
    {"espanol": "SLOVAKIA", "ingles": "ESLOVAQUIA"},
    {"espanol": "SLOVENIA", "ingles": "ESLOVENIA"},
    {"espanol": "SOMALIA", "ingles": "SOMALIA"},
    {"espanol": "SOUTH AFRICA", "ingles": "SUDÁFRICA"},
    {"espanol": "SPAIN", "ingles": "ESPAÑA"},
    {"espanol": "SRI LANKA", "ingles": "SRI LANKA"},
    {"espanol": "SUDAN", "ingles": "SUDÁN"},
    {"espanol": "SOUTH SUDAN", "ingles": "SUDÁN DEL SUR"},
    {"espanol": "SURINAME", "ingles": "SURINAM"},
    {"espanol": "SWEDEN", "ingles": "SUECIA"},
    {"espanol": "SWITZERLAND", "ingles": "SUIZA"},
    {"espanol": "SYRIAN ARAB REPUBLIC", "ingles": "SIRIA"},
    {"espanol": "THAILAND", "ingles": "TAILANDIA"},
    {"espanol": "THE UNITED KINGDOM", "ingles": "REINO UNIDO"},
    {"espanol": "TIMOR-LESTE", "ingles": "TIMOR ORIENTAL"},
    {"espanol": "TOGO", "ingles": "TOGO"},
    {"espanol": "TRINIDAD AND TOBAGO", "ingles": "TRINIDAD Y TOBAGO"},
    {"espanol": "TUNISIA", "ingles": "TÚNEZ"},
    {"espanol": "TURKEY", "ingles": "TURQUÍA"},
    {"espanol": "TURKS AND CAICOS ISLANDS", "ingles": "TURCOS Y CAICOS (RU)"},
    {"espanol": "UGANDA", "ingles": "UGANDA"},
    {"espanol": "UKRAINE", "ingles": "UCRANIA"},
    {"espanol": "UNITED ARAB EMIRATES", "ingles": "EMIRATOS ÁRABES UNIDOS"},
    {"espanol": "UNITED REPUBLIC OF TANZANIA", "ingles": "TANZANIA"},
    {"espanol": "UNITED STATES OF AMERICA", "ingles": "ESTADOS UNIDOS"},
    {"espanol": "UNITED STATES VIRGIN ISLANDS", "ingles": "ISLAS VÍRGENES ESTADOUNIDENSES (EEUU)"},
    {"espanol": "URUGUAY", "ingles": "URUGUAY"},
    {"espanol": "UZBEKISTAN", "ingles": "UZBEKISTÁN"},
    {"espanol": "VENEZUELA (BOLIVARIAN REPUBLIC OF)", "ingles": "VENEZUELA"},
    {"espanol": "VIET NAM", "ingles": "VIET NAM"},
    {"espanol": "YEMEN", "ingles": "YEMEN"},
    {"espanol": "ZAMBIA", "ingles": "ZAMBIA"},
    {"espanol": "ZIMBABWE", "ingles": "ZIMBABWE"},
    {"espanol": "GRAND TOTAL", "ingles": "TOTAL"}
]


def get_covid_place(place, covid_places):
    for covid_place in places:
        if place in covid_place["espanol"] and covid_place["ingles"] not in covid_places:
            return covid_place["ingles"]
    return None


def is_covid_place(place):
    for covid_place in places:
        if place == covid_place["espanol"]:
            return True

    return False
